#!/usr/bin/env bash
set -euo pipefail

export NBAML_PRESEASON_N_ITER_SINGLE="${NBAML_PRESEASON_N_ITER_SINGLE:-2}"
export NBAML_PRESEASON_CV_SPLITS="${NBAML_PRESEASON_CV_SPLITS:-2}"
export NBAML_BLEND_WEIGHT_STEP="${NBAML_BLEND_WEIGHT_STEP:-0.20}"
export NBAML_DISABLE_LGBM="${NBAML_DISABLE_LGBM:-1}"
export NBAML_SELECTION_METRIC="${NBAML_SELECTION_METRIC:-usd_mae}"
export NBAML_FORCE_RETRAIN="${NBAML_FORCE_RETRAIN:-1}"

echo "Running fast dev preset (performance-only preseason models)..."
echo "NBAML_PRESEASON_N_ITER_SINGLE=${NBAML_PRESEASON_N_ITER_SINGLE}"
echo "NBAML_PRESEASON_CV_SPLITS=${NBAML_PRESEASON_CV_SPLITS}"
echo "NBAML_BLEND_WEIGHT_STEP=${NBAML_BLEND_WEIGHT_STEP}"
echo "NBAML_DISABLE_LGBM=${NBAML_DISABLE_LGBM}"
echo "NBAML_FORCE_RETRAIN=${NBAML_FORCE_RETRAIN}"
echo

bash run_all_models.sh
